//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MONEY_GUARDIAN.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MONEY_GUARDIAN.Domain.Exceptions.MessagesExceptions", typeof(MessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor debe ser mayor o igual a cero.
        /// </summary>
        public static string AmountGreatherThanZero {
            get {
                return ResourceManager.GetString("AmountGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El total del presupuesto NO puede superar el total de los depositos.
        /// </summary>
        public static string BudgetExceedsDeposits {
            get {
                return ResourceManager.GetString("BudgetExceedsDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un tipo de gasto con ese nombre.
        /// </summary>
        public static string ExistExpenseType {
            get {
                return ResourceManager.GetString("ExistExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un fondo monetario con este nombre y tipo.
        /// </summary>
        public static string ExistMonetaryFund {
            get {
                return ResourceManager.GetString("ExistMonetaryFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El gasto NO puede superar el presupuesto.
        /// </summary>
        public static string ExpenseExceedsBudget {
            get {
                return ResourceManager.GetString("ExpenseExceedsBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña invalidos.
        /// </summary>
        public static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de mes invalido.
        /// </summary>
        public static string MonthInvalid {
            get {
                return ResourceManager.GetString("MonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el presupuesto.
        /// </summary>
        public static string NotExistBudget {
            get {
                return ResourceManager.GetString("NotExistBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el deposito.
        /// </summary>
        public static string NotExistDeposit {
            get {
                return ResourceManager.GetString("NotExistDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el detalle del gasto.
        /// </summary>
        public static string NotExistExpenseDetail {
            get {
                return ResourceManager.GetString("NotExistExpenseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el gasto.
        /// </summary>
        public static string NotExistExpenseHeader {
            get {
                return ResourceManager.GetString("NotExistExpenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el tipo de gasto.
        /// </summary>
        public static string NotExistExpenseType {
            get {
                return ResourceManager.GetString("NotExistExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el fondo monetario.
        /// </summary>
        public static string NotExistMonetaryFund {
            get {
                return ResourceManager.GetString("NotExistMonetaryFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el usuario.
        /// </summary>
        public static string NotExistUser {
            get {
                return ResourceManager.GetString("NotExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo puede existir un presupeuesto por usuario, tipo de gasto en un mes.
        /// </summary>
        public static string UniqueMonthlyBudget {
            get {
                return ResourceManager.GetString("UniqueMonthlyBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El año ingresado debe ser mayor o igual al 2020.
        /// </summary>
        public static string YearInvalid {
            get {
                return ResourceManager.GetString("YearInvalid", resourceCulture);
            }
        }
    }
}
