//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MONEY_GUARDIAN.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MONEY_GUARDIAN.Infrastructure.Constants.MessageConstants", typeof(MessageConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    b.[Id]
        ///      ,b.[UserId]
        ///   ,u.name as &apos;userName&apos;
        ///      ,b.[ExpenseTypeId]
        ///   ,et.Name as &apos;ExpenseTypeName&apos;
        ///      ,b.[Month]
        ///      ,b.[Year]
        ///      ,b.[Amount]
        ///  FROM [MONEY_GUARDIAN].[dbo].[Budgets] as b
        ///  inner join MONEY_GUARDIAN.dbo.Users as u on u.Id = b.UserId
        ///  inner join MONEY_GUARDIAN.dbo.ExpenseTypes as et on et.Id = b.ExpenseTypeId
        ///  {0}.
        /// </summary>
        internal static string GetBudgets {
            get {
                return ResourceManager.GetString("GetBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    d.[Id]
        ///      ,d.[Date]
        ///      ,d.[MonetaryFundId]
        ///   , m.[Name] as MonetaryFundName
        ///      ,d.[Amount]
        ///  FROM [MONEY_GUARDIAN].[dbo].[Deposits] as d
        ///  inner join MONEY_GUARDIAN.dbo.MonetaryFunds as m on m.Id = d.MonetaryFundId
        ///  {0}.
        /// </summary>
        internal static string GetDeposits {
            get {
                return ResourceManager.GetString("GetDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  select 
        /// eh.Id,
        /// eh.Date,
        /// eh.MonetaryFundId,
        /// mf.Name as MonetaryFundName,
        /// eh.UserId,
        /// u.Username,
        /// eh.Observations as observation,
        /// eh.Merchant,
        /// eh.DocumentType,
        /// ed.Amount,
        /// ed.ExpenseTypeId,
        /// et.Name as ExpenseTypeName
        ///  from [MONEY_GUARDIAN].[dbo].[ExpenseHeaders] as eh
        ///  inner join [MONEY_GUARDIAN].[dbo].MonetaryFunds as mf on mf.Id = eh.MonetaryFundId
        ///  inner join [MONEY_GUARDIAN].[dbo].Users as u on u.Id = eh.UserId
        ///  inner join [MONEY_GUARDIAN].[dbo].[ExpenseDetails] as ed on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetExpenseDetail {
            get {
                return ResourceManager.GetString("GetExpenseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (1000) [Id]
        ///      ,[Code]
        ///      ,[Name]
        ///  FROM [MONEY_GUARDIAN].[dbo].[ExpenseTypes]
        ///  {0}.
        /// </summary>
        internal static string GetExpenseType {
            get {
                return ResourceManager.GetString("GetExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  [Id]
        ///      ,[Name]
        ///      ,[Type]
        ///  FROM [MONEY_GUARDIAN].[dbo].[MonetaryFunds]
        ///  {0}.
        /// </summary>
        internal static string GetMonetaryFund {
            get {
                return ResourceManager.GetString("GetMonetaryFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from (
        /// select 
        ///  d.Id,
        ///  d.Date,
        ///  &apos;Deposito&apos; as TypeTransaction,
        ///  d.Amount
        /// from [MONEY_GUARDIAN].[dbo].[Deposits] as d
        /// union
        /// SELECT 
        ///  eh.Id,
        ///  eh.Date,
        ///  &apos;Gasto&apos; as TypeTransaction,
        ///  sum(ed.Amount)
        /// FROM [MONEY_GUARDIAN].[dbo].[ExpenseHeaders] as eh
        /// inner join [MONEY_GUARDIAN].[dbo].[ExpenseDetails] as ed on ed.ExpenseHeaderId = eh.Id
        /// group By eh.Id,eh.Date
        ///) as s
        ///{0}.
        /// </summary>
        internal static string GetReport {
            get {
                return ResourceManager.GetString("GetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from
        ///(
        ///select  
        /// et.[Name],
        /// EOMONTH(DATEFROMPARTS(b.year, b.month, 1)) as date,
        /// sum(b.Amount) as amount,
        /// &apos;Presupestado&apos; as description
        ///from ExpenseTypes as et
        ///inner join Budgets as b on b.ExpenseTypeId = et.id
        ///group by et.Name,EOMONTH(DATEFROMPARTS(b.year, b.month, 1))
        ///union
        ///select 
        /// et.[Name],
        /// eh.Date,
        /// sum(ed.Amount) as amount,
        /// &apos;Ejecutado&apos; as description
        ///from ExpenseTypes as et
        ///inner join ExpenseDetails as ed on ed.ExpenseTypeId = et.Id
        ///inner join ExpenseHeaders as eh on eh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetReportChart {
            get {
                return ResourceManager.GetString("GetReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  [Id]
        ///      ,[Name]
        ///      ,[Username]    
        ///  FROM [MONEY_GUARDIAN].[dbo].[Users]
        ///  {0}.
        /// </summary>
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
    }
}
